<?php

	$height = Mage::getStoreConfig('slider/option/height')?Mage::getStoreConfig('slider/option/height'):'300px'; 

	$width = Mage::getStoreConfig('slider/option/width')?Mage::getStoreConfig('slider/option/width'):'100%';

	$speed = Mage::getStoreConfig('slider/option/speed');

	$loop = Mage::getStoreConfig('slider/option/loop');
	$loop = $loop == 0 ? 'false' : 'true';

	$indicator = Mage::getStoreConfig('slider/option/indicator');
	$indicator = $indicator == 0 ? 'none' : '';

	$control = Mage::getStoreConfig('slider/option/control');
	$control = $control == 0 ? 'none' : '';
?>



<div class="container-fluid clearfix">
	<div class="row">
		<div class="col-sm-12" style="padding: 0px;">
			<div class="slides">
				<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="<?php echo $speed; ?>" data-wrap="<?php echo $loop; ?>" style="width:<?php echo $width; ?>">
					<?php $collection = $this->getBanner(); ?>
					
					<ol class='carousel-indicators' style="display:<?php echo $indicator; ?>">
						<?php
						for($i=0;$i<$collection->count();$i++)
							echo "<li data-target='#carousel-example-generic' data-slide-to='".$i."'></li>";
						?>
					</ol>
					<div class="carousel-inner">
						<?php
						foreach($collection as $item)
						{
						?>
							<div class="item"><img style="width: 100%;height:<?php echo $height; ?>; overflow: hidden;" src="<?php echo Mage::helper('banner')->getImage($item) ?>" alt="..." />
								<div class="carousel-caption">
									<h1><?php echo $item->getData('image_title'); ?></h1>
									<p><?php echo $item->getData('image_caption'); ?></p>
									<a href="<?php echo $item->getData('image_link'); ?>" class="button">BROWSE&lt; </a>
								</div>
							</div>
						<?php
						}
						?>
					</div>
					<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev" style="display:<?php echo $control; ?>">
					    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					    <span class="sr-only">Previous</span>
				  	</a>
				  	<a  class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next" style="display:<?php echo $control; ?>">
					    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					    <span class="sr-only">Next</span>
				  	</a>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	jQuery('.carousel-inner .item').first().addClass('active');
	jQuery(".carousel-indicators li").first().addClass('active');
});

</script>